import { GameRom, DownloadTask, CloudSaveEvent, ServerConfig, SmbFileItem } from './types';

export const INITIAL_SERVER_CONFIG: ServerConfig = {
  serverUrl: 'http://192.168.1.100:8080',
  username: 'retro_player',
  apiKey: 'rm_live_7x89fa0129bc412de88f01b9',
  isTokenMasked: true,
  pingMs: 14,
  autoSyncSaves: true,
  smbShareUrl: 'smb://192.168.1.50/roms',
  storageMount: '/roms2', // Secondary TF2 SD card by default
  tf2SyncPath: '/roms2/tf2/romm_sync/',
  theme: 'cyan', // Can be switched to 'amber' or 'paper'
  conflictResolution: 'Keep Newer Save',
  githubRepo: 'Cavephar/RomM-R36S',
  githubBranch: 'main',
  currentVersion: 'v1.3.0',
};

export const INITIAL_GAMES: GameRom[] = [
  {
    id: 'snes-smw2',
    title: "Super Mario World 2: Yoshi's Island",
    subtitle: "Yoshi's Island (USA) • v1.1",
    platform: 'snes',
    releaseYear: 1995,
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    size: '1.4M',
    sizeBytes: 1468006,
    status: 'installed',
    rating: 4.9,
    isFavorite: true,
    crc32: '0EC0C93A',
    chip: 'Super FX 2',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'synced',
    lastSaveSync: '2m ago',
    saveSlot: 'Slot #01 (Auto)',
    playtime: '14h 22m (87%)',
    description: 'When the evil Kamek attempts to kidnap Baby Mario and Baby Luigi, Yoshi and the clan must embark on a treacherous journey through handmade prehistoric lands.',
    coverUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCx4rNG2741jVq5MlH9RjSIU1jWXJR8YTIcPga3rGUf7R8kJ3L5jDJYhwC2y6Y1RYIUzY0gSDw1MQ4D9IHFhkOrkC5rherM3DMxW7mMR4_3wXWr1_VuzvWavKzktsRnMi2mpM8E8vZTVRfNsKmeSX0JOqXNZhp78-N5jkirO8x89rV0_JgIgwYpyFt-ZJ47GFbMS4krltGKkiqJ7M8ovZ3BTO6riRxai1Rm4QevSR5_ljZWNj8lKK-S',
    romFileName: 'Super Mario World 2 - Yoshi\'s Island (USA) (Rev 1).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/Super Mario World 2 - Yoshi\'s Island (USA).sfc',
  },
  {
    id: 'snes-chrono',
    title: 'Chrono Trigger',
    subtitle: '1995 • Square Soft • NTSC',
    platform: 'snes',
    releaseYear: 1995,
    developer: 'Square',
    publisher: 'Square Soft',
    size: '4.0M',
    sizeBytes: 4194304,
    status: 'installed',
    rating: 5.0,
    isFavorite: true,
    crc32: '2D20FFC0',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'synced',
    lastSaveSync: '1h ago',
    saveSlot: 'Slot #02',
    playtime: '28h 45m (94%)',
    description: 'A young man accidentally travels through time to save the planet from an extraterrestrial parasite known as Lavos.',
    coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Chrono Trigger (USA).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/Chrono Trigger (USA).sfc',
  },
  {
    id: 'snes-alttp',
    title: 'The Legend of Zelda: A Link to the Past',
    subtitle: '1991 • Nintendo • Rev 1',
    platform: 'snes',
    releaseYear: 1991,
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    size: '1.5M',
    sizeBytes: 1572864,
    status: 'downloading',
    downloadProgress: 68,
    downloadSpeed: '1.2MB/s',
    rating: 4.9,
    isFavorite: false,
    crc32: '777DD581',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'local_ahead',
    lastSaveSync: 'Yesterday',
    saveSlot: 'Slot #01',
    playtime: '08h 10m (45%)',
    description: 'Link must travel between the Light World and the Dark World to defeat the evil sorcerer Agahnim and Ganon.',
    coverUrl: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Legend of Zelda, The - A Link to the Past (USA).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/Legend of Zelda, The - A Link to the Past (USA).sfc',
  },
  {
    id: 'snes-metroid',
    title: 'Super Metroid',
    subtitle: '1994 • Nintendo R&D1',
    platform: 'snes',
    releaseYear: 1994,
    developer: 'Nintendo R&D1',
    publisher: 'Nintendo',
    size: '3.2M',
    sizeBytes: 3355443,
    status: 'cloud',
    rating: 5.0,
    isFavorite: false,
    crc32: '8F902A1C',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'synced',
    lastSaveSync: '12m ago',
    saveSlot: 'Slot #01',
    playtime: '06h 18m (35%)',
    description: 'Bounty hunter Samus Aran travels to planet Zebes to retrieve the stolen infant Metroid from Space Pirate leader Ridley.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Super Metroid (Japan, USA) (En,Ja).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/Super Metroid.sfc',
  },
  {
    id: 'snes-dkc',
    title: 'Donkey Kong Country',
    subtitle: '1994 • Rareware',
    platform: 'snes',
    releaseYear: 1994,
    developer: 'Rareware',
    publisher: 'Nintendo',
    size: '3.8M',
    sizeBytes: 3984588,
    status: 'installed',
    rating: 4.8,
    isFavorite: true,
    crc32: 'F3F4D201',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'synced',
    lastSaveSync: '3d ago',
    saveSlot: 'Slot #01',
    playtime: '11h 05m (72%)',
    description: 'Donkey Kong and Diddy Kong recover their stolen banana hoard from the evil King K. Rool and the Kremlings.',
    coverUrl: 'https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Donkey Kong Country (USA) (Rev 2).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/Donkey Kong Country (USA).sfc',
  },
  {
    id: 'snes-earthbound',
    title: 'EarthBound (Mother 2)',
    subtitle: '1994 • Ape / HAL Laboratory',
    platform: 'snes',
    releaseYear: 1994,
    developer: 'Ape / HAL',
    publisher: 'Nintendo',
    size: '4.2M',
    sizeBytes: 4404019,
    status: 'cloud',
    rating: 4.9,
    isFavorite: false,
    crc32: '588C02B9',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'none',
    lastSaveSync: 'Never',
    saveSlot: 'None',
    playtime: '0h 00m (0%)',
    description: 'Ness and his companions travel across the world using Sound Stone melodies to halt the universal cosmic conqueror Giygas.',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    romFileName: 'EarthBound (USA).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/EarthBound (USA).sfc',
  },
  {
    id: 'snes-megamanx',
    title: 'Mega Man X',
    subtitle: '1993 • Capcom',
    platform: 'snes',
    releaseYear: 1993,
    developer: 'Capcom',
    publisher: 'Capcom',
    size: '2.0M',
    sizeBytes: 2097152,
    status: 'installed',
    rating: 4.9,
    isFavorite: false,
    crc32: '93D53C12',
    region: 'USA / NTSC',
    core: 'Snes9x 2010',
    saveSyncStatus: 'synced',
    lastSaveSync: '4d ago',
    saveSlot: 'Slot #01',
    playtime: '04h 30m (60%)',
    description: 'X joins the Maverick Hunters alongside Zero to stop the rogue Sigma and his rebellion against humanity.',
    coverUrl: 'https://images.unsplash.com/photo-1612287233215-0210e74b3353?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Mega Man X (USA).sfc',
    smbPath: 'smb://192.168.1.50/roms/snes/Mega Man X (USA).sfc',
  },
  // GBA
  {
    id: 'gba-pokemon-emerald',
    title: 'Pokemon Emerald Version',
    subtitle: '2004 • Game Freak • Hoenn',
    platform: 'gba',
    releaseYear: 2004,
    developer: 'Game Freak',
    publisher: 'Nintendo / The Pokemon Company',
    size: '16.0M',
    sizeBytes: 16777216,
    status: 'cloud',
    rating: 4.9,
    isFavorite: true,
    crc32: 'F3AE088B',
    region: 'USA',
    core: 'mGBA',
    saveSyncStatus: 'synced',
    lastSaveSync: '1h ago',
    saveSlot: 'Slot #01',
    playtime: '42h 12m (80%)',
    description: 'Embark on an adventure through the Hoenn region, confronting Team Magma and Team Aqua to awaken Rayquaza.',
    coverUrl: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Pokemon - Emerald Version (USA, Europe).gba',
    smbPath: 'smb://192.168.1.50/roms/gba/Pokemon Emerald.gba',
  },
  {
    id: 'gba-metroid-fusion',
    title: 'Metroid Fusion',
    subtitle: '2002 • Nintendo R&D1',
    platform: 'gba',
    releaseYear: 2002,
    developer: 'Nintendo R&D1',
    publisher: 'Nintendo',
    size: '8.0M',
    sizeBytes: 8388608,
    status: 'installed',
    rating: 4.8,
    isFavorite: false,
    crc32: '617511B4',
    region: 'USA',
    core: 'mGBA',
    saveSyncStatus: 'synced',
    lastSaveSync: '5d ago',
    saveSlot: 'Slot #01',
    playtime: '05h 20m (100%)',
    description: 'Infected by the deadly X Parasite, Samus receives Metroid DNA and must cleanse the Biologic Space Laboratories.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Metroid Fusion (USA).gba',
    smbPath: 'smb://192.168.1.50/roms/gba/Metroid Fusion.gba',
  },
  // PS1
  {
    id: 'ps1-castlevania',
    title: 'Castlevania: Symphony of the Night',
    subtitle: '1997 • Konami • NTSC-U',
    platform: 'ps1',
    releaseYear: 1997,
    developer: 'Konami Computer Entertainment Tokyo',
    publisher: 'Konami',
    size: '512M',
    sizeBytes: 536870912,
    status: 'downloading',
    downloadProgress: 67,
    downloadSpeed: '4.8 MB/s',
    rating: 5.0,
    isFavorite: true,
    crc32: 'A03991F2',
    region: 'USA',
    core: 'DuckStation / PCSX-ReARMed',
    saveSyncStatus: 'synced',
    lastSaveSync: '30m ago',
    saveSlot: 'Memory Card 1 (Slot 01)',
    playtime: '19h 30m (200.6%)',
    description: 'Dracula\'s castle has reappeared. Alucard, the dhampir son of Dracula, awakens from slumber to inspect the castle and destroy his father.',
    coverUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Castlevania - Symphony of the Night (USA) (Track 1).chd',
    smbPath: 'smb://192.168.1.50/roms/psx/Castlevania SotN.chd',
  },
  {
    id: 'ps1-mgs',
    title: 'Metal Gear Solid (Disc 1)',
    subtitle: '1998 • Konami / KCEJ',
    platform: 'ps1',
    releaseYear: 1998,
    developer: 'KCEJ',
    publisher: 'Konami',
    size: '480M',
    sizeBytes: 503316480,
    status: 'cloud',
    rating: 4.9,
    isFavorite: true,
    crc32: 'C391104A',
    region: 'USA',
    core: 'DuckStation / PCSX-ReARMed',
    saveSyncStatus: 'none',
    lastSaveSync: 'Never',
    saveSlot: 'None',
    playtime: '0h 00m',
    description: 'Solid Snake infiltrates a nuclear weapons facility on Shadow Moses island to neutralize the terrorist threat of FOXHOUND.',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Metal Gear Solid (USA) (Disc 1) (v1.1).chd',
    smbPath: 'smb://192.168.1.50/roms/psx/Metal Gear Solid (Disc 1).chd',
  },
  // N64
  {
    id: 'n64-oot',
    title: 'The Legend of Zelda: Ocarina of Time',
    subtitle: '1998 • Nintendo EAD',
    platform: 'n64',
    releaseYear: 1998,
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    size: '32M',
    sizeBytes: 33554432,
    status: 'installed',
    rating: 5.0,
    isFavorite: true,
    crc32: 'EC7011B7',
    region: 'USA',
    core: 'Mupen64Plus-Next',
    saveSyncStatus: 'synced',
    lastSaveSync: '2d ago',
    saveSlot: 'Slot #01 (Auto)',
    playtime: '34h 10m (100%)',
    description: 'As Link, players explore the mythical land of Hyrule to stop Ganondorf by retrieving the Master Sword and awakening the Six Sages.',
    coverUrl: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Legend of Zelda, The - Ocarina of Time (USA) (Rev 2).z64',
    smbPath: 'smb://192.168.1.50/roms/n64/Zelda Ocarina of Time.z64',
  },
  // GENESIS
  {
    id: 'gen-sonic2',
    title: 'Sonic the Hedgehog 2',
    subtitle: '1992 • Sonic Team / STI',
    platform: 'genesis',
    releaseYear: 1992,
    developer: 'Sonic Team',
    publisher: 'Sega',
    size: '1.0M',
    sizeBytes: 1048576,
    status: 'installed',
    rating: 4.8,
    isFavorite: false,
    crc32: 'A4A41B20',
    region: 'USA / Europe',
    core: 'Genesis Plus GX',
    saveSyncStatus: 'synced',
    lastSaveSync: '1w ago',
    saveSlot: 'Slot #01',
    playtime: '03h 40m',
    description: 'Sonic and his new sidekick Miles "Tails" Prower journey across West Side Island to stop Dr. Robotnik\'s Death Egg.',
    coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    romFileName: 'Sonic the Hedgehog 2 (World) (Rev A).md',
    smbPath: 'smb://192.168.1.50/roms/genesis/Sonic 2.md',
  },
  // ARCADE
  {
    id: 'arc-sf3',
    title: 'Street Fighter III: 3rd Strike',
    subtitle: '1999 • Capcom (CPS-3)',
    platform: 'arcade',
    releaseYear: 1999,
    developer: 'Capcom',
    publisher: 'Capcom',
    size: '68M',
    sizeBytes: 71303168,
    status: 'installed',
    rating: 5.0,
    isFavorite: true,
    crc32: '67EF10A9',
    region: 'World (CPS-3)',
    core: 'FB Neo',
    saveSyncStatus: 'none',
    lastSaveSync: 'N/A',
    saveSlot: 'NVRAM',
    playtime: '18h 50m',
    description: 'The pinnacle of Capcom 2D competitive fighting with legendary parrying mechanics and fluid animation.',
    coverUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80',
    romFileName: 'sfiii3nr1.zip',
    smbPath: 'smb://192.168.1.50/roms/arcade/sfiii3nr1.zip',
  }
];

export const INITIAL_DOWNLOADS: DownloadTask[] = [
  {
    id: 'dl-1',
    romId: 'ps1-castlevania',
    title: 'Castlevania: Symphony of the Night',
    platform: 'ps1',
    size: '512 MB',
    currentBytes: 342 * 1024 * 1024,
    totalBytes: 512 * 1024 * 1024,
    progress: 67,
    speed: '4.8 MB/s',
    eta: '1m 12s',
    status: 'downloading',
  },
  {
    id: 'dl-2',
    romId: 'ps1-mgs',
    title: 'Metal Gear Solid (Disc 1)',
    platform: 'ps1',
    size: '480 MB',
    currentBytes: 0,
    totalBytes: 480 * 1024 * 1024,
    progress: 0,
    speed: '0.0 MB/s',
    eta: 'Queued #2',
    status: 'queued',
  },
  {
    id: 'dl-3',
    romId: 'gba-pokemon-emerald',
    title: 'Pokemon Emerald Version',
    platform: 'gba',
    size: '16 MB',
    currentBytes: 0,
    totalBytes: 16 * 1024 * 1024,
    progress: 0,
    speed: '0.0 MB/s',
    eta: 'Queued #3',
    status: 'queued',
  },
  {
    id: 'dl-4',
    romId: 'n64-oot',
    title: 'The Legend of Zelda: Ocarina of Time',
    platform: 'n64',
    size: '32 MB',
    currentBytes: 32 * 1024 * 1024,
    totalBytes: 32 * 1024 * 1024,
    progress: 100,
    speed: 'Done',
    eta: 'Complete',
    status: 'done',
  },
];

export const INITIAL_SAVE_EVENTS: CloudSaveEvent[] = [
  {
    id: 'ev-1',
    gameTitle: 'Super Metroid (Slot 1)',
    platform: 'snes',
    slot: 'Slot #01',
    timeAgo: '12m ago',
    direction: 'bidirectional',
    crc32: '#8F902A',
    status: 'verified',
    details: 'RomM Cloud <=> SD2/snes (Verified 0 errors)',
  },
  {
    id: 'ev-2',
    gameTitle: "Super Mario World 2: Yoshi's Island",
    platform: 'snes',
    slot: 'Slot #01',
    timeAgo: '2m ago',
    direction: 'upload',
    crc32: '#0EC0C9',
    status: 'synced',
    details: 'Uploaded to RomM Cloud (Slot 1 OK)',
  },
  {
    id: 'ev-3',
    gameTitle: 'Pokemon Emerald Version',
    platform: 'gba',
    slot: 'Slot #01',
    timeAgo: '1h ago',
    direction: 'bidirectional',
    crc32: '#F3AE08',
    status: 'synced',
    details: 'Cloud Save: Today 18:30',
  },
  {
    id: 'ev-4',
    gameTitle: 'Chrono Trigger',
    platform: 'snes',
    slot: 'Slot #02',
    timeAgo: '1h ago',
    direction: 'download',
    crc32: '#2D20FF',
    status: 'verified',
    details: 'Synced from RomM server',
  }
];

export const SMB_FILE_SYSTEM: Record<string, SmbFileItem[]> = {
  '/': [
    { name: 'roms', type: 'directory', path: '/roms' },
    { name: 'bios', type: 'directory', path: '/bios' },
    { name: 'saves', type: 'directory', path: '/saves' },
    { name: 'romm_backup.tar.gz', type: 'file', size: '2.4 GB', path: '/romm_backup.tar.gz' },
  ],
  '/roms': [
    { name: 'snes', type: 'directory', platform: 'snes', path: '/roms/snes' },
    { name: 'gba', type: 'directory', platform: 'gba', path: '/roms/gba' },
    { name: 'psx', type: 'directory', platform: 'ps1', path: '/roms/psx' },
    { name: 'n64', type: 'directory', platform: 'n64', path: '/roms/n64' },
    { name: 'genesis', type: 'directory', platform: 'genesis', path: '/roms/genesis' },
    { name: 'arcade', type: 'directory', platform: 'arcade', path: '/roms/arcade' },
  ],
  '/roms/snes': [
    { name: 'Super Mario World 2 - Yoshi\'s Island (USA) (Rev 1).sfc', type: 'file', size: '1.4 MB', platform: 'snes', path: '/roms/snes/Super Mario World 2.sfc' },
    { name: 'Chrono Trigger (USA).sfc', type: 'file', size: '4.0 MB', platform: 'snes', path: '/roms/snes/Chrono Trigger.sfc' },
    { name: 'Legend of Zelda, The - A Link to the Past (USA).sfc', type: 'file', size: '1.5 MB', platform: 'snes', path: '/roms/snes/Zelda ALTTP.sfc' },
    { name: 'Super Metroid (USA).sfc', type: 'file', size: '3.2 MB', platform: 'snes', path: '/roms/snes/Super Metroid.sfc' },
    { name: 'Donkey Kong Country (USA).sfc', type: 'file', size: '3.8 MB', platform: 'snes', path: '/roms/snes/Donkey Kong Country.sfc' },
    { name: 'EarthBound (USA).sfc', type: 'file', size: '4.2 MB', platform: 'snes', path: '/roms/snes/EarthBound.sfc' },
    { name: 'Mega Man X (USA).sfc', type: 'file', size: '2.0 MB', platform: 'snes', path: '/roms/snes/Mega Man X.sfc' },
    { name: 'Secret of Mana (USA).sfc', type: 'file', size: '2.0 MB', platform: 'snes', path: '/roms/snes/Secret of Mana.sfc' },
    { name: 'Super Castlevania IV (USA).sfc', type: 'file', size: '1.2 MB', platform: 'snes', path: '/roms/snes/Super Castlevania IV.sfc' },
  ],
  '/roms/gba': [
    { name: 'Pokemon - Emerald Version (USA, Europe).gba', type: 'file', size: '16.0 MB', platform: 'gba', path: '/roms/gba/Pokemon Emerald.gba' },
    { name: 'Metroid Fusion (USA).gba', type: 'file', size: '8.0 MB', platform: 'gba', path: '/roms/gba/Metroid Fusion.gba' },
    { name: 'Golden Sun (USA).gba', type: 'file', size: '8.0 MB', platform: 'gba', path: '/roms/gba/Golden Sun.gba' },
    { name: 'Castlevania - Aria of Sorrow (USA).gba', type: 'file', size: '8.0 MB', platform: 'gba', path: '/roms/gba/Castlevania AoS.gba' },
    { name: 'The Legend of Zelda - The Minish Cap (USA).gba', type: 'file', size: '16.0 MB', platform: 'gba', path: '/roms/gba/Zelda Minish Cap.gba' },
  ],
  '/roms/psx': [
    { name: 'Castlevania - Symphony of the Night (USA).chd', type: 'file', size: '512 MB', platform: 'ps1', path: '/roms/psx/Castlevania SotN.chd' },
    { name: 'Metal Gear Solid (USA) (Disc 1).chd', type: 'file', size: '480 MB', platform: 'ps1', path: '/roms/psx/MGS Disc 1.chd' },
    { name: 'Final Fantasy VII (USA) (Disc 1).chd', type: 'file', size: '540 MB', platform: 'ps1', path: '/roms/psx/FF7 Disc 1.chd' },
    { name: 'Silent Hill (USA).chd', type: 'file', size: '360 MB', platform: 'ps1', path: '/roms/psx/Silent Hill.chd' },
  ],
};
